"""empty message

Revision ID: 0a10b018db1c
Revises: e7248d047a76
Create Date: 2020-10-21 11:59:20.169710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a10b018db1c'
down_revision = 'e7248d047a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access', sa.String(), nullable=True))
    op.execute("UPDATE users SET access = 'admin'")
    op.alter_column('users', 'access', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access')
    # ### end Alembic commands ###
