"""empty message

Revision ID: 1d0dd44fae2f
Revises: aeda52d58605
Create Date: 2020-09-24 13:23:45.917798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d0dd44fae2f'
down_revision = 'aeda52d58605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['uid'], ['users.id'], name='fk_uid'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_tokens')
    # ### end Alembic commands ###
