"""empty message

Revision ID: 29ec61cd7944
Revises: 81069552aa2f
Create Date: 2020-09-25 09:55:41.442958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29ec61cd7944'
down_revision = '81069552aa2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_aoi', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_aoi', 'name')
    # ### end Alembic commands ###
