"""empty message

Revision ID: 391dd108d76d
Revises: 5b463edbfe07
Create Date: 2020-09-02 10:11:30.088841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '391dd108d76d'
down_revision = '5b463edbfe07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prediction_tiles', 'quadkey_geom', nullable=False, new_column_name='geom')
    op.alter_column('prediction_tiles', 'quadkey', existing_type=sa.VARCHAR(), nullable=True)

    op.drop_index('idx_prediction_tiles_centroid', table_name='prediction_tiles')
    op.drop_column('prediction_tiles', 'centroid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prediction_tiles', 'geom', nullable=False, new_column_name='quadkey_geom')
    op.add_column('prediction_tiles', sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=True))

    op.create_index('idx_prediction_tiles_centroid', 'prediction_tiles', ['centroid'], unique=False)
    # ### end Alembic commands ###
