"""empty message

Revision ID: 50d0eb11ed3c
Revises: 0a10b018db1c
Create Date: 2020-10-27 09:01:23.971490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50d0eb11ed3c'
down_revision = '0a10b018db1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'notes')
    # ### end Alembic commands ###
