"""empty message

Revision ID: 546869fd8dca
Revises: c8908856c3cb
Create Date: 2020-10-06 12:33:30.637025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '546869fd8dca'
down_revision = 'c8908856c3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_access',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model_id', sa.BigInteger(), nullable=False),
        sa.Column('uid', sa.BigInteger(), nullable=False),
        sa.Column('access', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], name='fk_models'),
        sa.ForeignKeyConstraint(['uid'], ['users.id'], name='fk_users'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_access')
    # ### end Alembic commands ###
