"""empty message

Revision ID: 5b463edbfe07
Revises: ff97cfa4b1c3
Create Date: 2020-08-25 11:00:43.741447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b463edbfe07'
down_revision = 'ff97cfa4b1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('hint', sa.String(), nullable=True))
    op.execute("UPDATE predictions SET hint = 'prediction'")
    op.alter_column('predictions', 'hint', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'hint')
    # ### end Alembic commands ###
