"""empty message

Revision ID: 81069552aa2f
Revises: 1d0dd44fae2f
Create Date: 2020-09-25 08:58:59.796845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '81069552aa2f'
down_revision = '1d0dd44fae2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_aoi',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model_id', sa.BigInteger(), nullable=False),
        sa.Column('pred_id', sa.BigInteger(), nullable=False),
        sa.Column('bounds', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
        sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], name='fk_models'),
        sa.ForeignKeyConstraint(['pred_id'], ['predictions.id'], name='fk_predictions'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_aoi')
    # ### end Alembic commands ###
