"""empty message

Revision ID: e7248d047a76
Revises: b6d042019f4f
Create Date: 2020-10-07 10:25:54.150964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7248d047a76'
down_revision = 'b6d042019f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO projects_access (model_id, uid, access)
            SELECT projects.id, users.id, 'admin' FROM projects, users WHERE users.name = 'machine'

    """)
    # ### end Alembic commands ###


def downgrade():
    print("No Changes")
    # ### end Alembic commands ###
